"""empty message

Revision ID: 7838bf6b0a99
Revises: 3d4de291d8dd
Create Date: 2021-09-08 21:52:56.431289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7838bf6b0a99'
down_revision = '3d4de291d8dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(length=120), nullable=False),
    sa.Column('standard_art', sa.Boolean(), nullable=True),
    sa.Column('standard_qty', sa.Integer(), nullable=True),
    sa.Column('alternate_art', sa.Boolean(), nullable=True),
    sa.Column('alternate_qty', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cards',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('card_id', 'user_id')
    )
    op.drop_table('card_set')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_set',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('series', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('printedTotal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ptcgoCode', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('releaseDate', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('updatedAt', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='card_set_pkey')
    )
    op.drop_table('cards')
    op.drop_table('card')
    # ### end Alembic commands ###
