"""empty message

Revision ID: 868046a967bd
Revises: 8322daa89414
Create Date: 2021-09-13 22:49:04.061026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868046a967bd'
down_revision = '8322daa89414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('card_card_id_key', 'card', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('card_card_id_key', 'card', ['card_id'])
    # ### end Alembic commands ###
