"""empty message

Revision ID: ec7ec8d1980c
Revises: 9cfdd31856ec
Create Date: 2021-07-27 20:47:27.426503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec7ec8d1980c'
down_revision = '9cfdd31856ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('series', sa.String(length=120), nullable=False),
    sa.Column('printedTotal', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('ptcgoCode', sa.String(length=120), nullable=False),
    sa.Column('releaseDate', sa.String(length=120), nullable=False),
    sa.Column('updatedAt', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('printedTotal'),
    sa.UniqueConstraint('ptcgoCode'),
    sa.UniqueConstraint('releaseDate'),
    sa.UniqueConstraint('series'),
    sa.UniqueConstraint('total'),
    sa.UniqueConstraint('updatedAt')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('set')
    # ### end Alembic commands ###
